apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
        - image: lsongseven/hello-world:v1.0-pre-stop
          name: hello-world
          resources: {}
          volumeMounts:
            - mountPath: "/data"
              name: data-storage
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","pre-stop.sh"]
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-pvc

